### ISSUE TITLE
List on probot app directory

### ISSUE THREAD

**Issue by bkeepers** [jarrodldavis/probot-gpg#34]
Hey @jarrodldavis, I'd love to get this app listed on the [probot website](https://probot.github.io/apps/)! Do you have an instance of it deployed anywhere? It's pretty [easy to deploy Probot apps](https://probot.github.io/docs/deployment/) on several different free services.

Are you interested in getting it listed? Here are the [docs for adding it](https://github.com/probot/probot.github.io/blob/master/CONTRIBUTING.md#adding-your-app).

**Comment by jarrodldavis** [comment]
I have a personal instance of it deployed for my repositories but I could look into getting a public instance deployed as well.

**Comment by jarrodldavis** [comment]
Alright, I've added `probot-gpg` in probot/probot.github.io#56.
